### ISSUE TITLE
query 조건 추가

### ISSUE THREAD

**Issue by dev-Rhea** [100-hours-a-week/5-bigbrother-slimdealz-be#70]
상품이 날짜별로 업데이트 됨에 따라, 오늘 날짜로 createdAt된 상품으로 조회되도록 조건 쿼리 추가.

**Comment by lky3004me** [comment]
/api/v1/vendor-list

조회시 날짜 관계 없이 모든 결과가 나옵니다.

날짜 관련해서 조건 다음과 같은 조건이 필요할 것 같다고 생각합니다.
1. 검색시, 오늘 날짜만 조회될 것
2. 혹은 검색시, 제품들 중 오늘 날짜 제품을 우선으로 나오고, 오늘 날짜가 없을 경우, 이전 날짜를 보여줄 것
