### ISSUE TITLE
QA: 검색어 입력 → 검색 결과 목록에서 같은 이름의 제품은 하나씩만 보이고, 이때 가격은 최저가여야 한다.

### ISSUE THREAD

**Issue by lky3004me** [100-hours-a-week/5-bigbrother-slimdealz-be#94]
https://www.notion.so/goormkdx/c4689935325745828ad37dcfb334d3cb?pvs=4

api 로직 변경 필요

**Comment by dev-Rhea** [comment]
<img width="994" alt="image" src="https://github.com/user-attachments/assets/6c3d8f2d-aecf-41d2-8281-42c8ec634a07">


포스트맨 테스트 완료
